services:
  teslamate:
    image: teslamate/teslamate:3.0.0@sha256:6569026b73bd657455bbec05965d07fa30b6d4d70eaab0bd5b343231c0429167
    container_name: teslamate
    restart: unless-stopped
    #ports:
    #  - 4000:4000
    volumes:
      - ${DOCKER_DATA_DIR}/teslamate/import:/opt/app/import
    environment:
      - TZ=Europe/Amsterdam
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${TESLAMATE_DB_PASSWORD}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-db
      - MQTT_HOST=teslamate-mosquitto
    cap_drop:
      - all
    depends_on:
      - teslamate-db
      - teslamate-mosquitto
    labels:
      - homepage.group=Media
      - homepage.name=TeslaMate
      - homepage.icon=teslamate.png
      - homepage.href=https://teslamate.${DOMAIN}/
      - homepage.description=Tesla data logger
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.teslamate.rule=Host(`teslamate.${DOMAIN}`)
      - traefik.http.routers.teslamate.entrypoints=websecure
      - traefik.http.routers.teslamate.tls=true
      - traefik.http.services.teslamate.loadbalancer.server.port=4000
    networks:
      - npm

  teslamate-db:
    image: postgres:18-trixie@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    container_name: teslamate-db
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=${TESLAMATE_DB_PASSWORD}
      - POSTGRES_DB=teslamate
    volumes:
      - ${DOCKER_DATA_DIR}/teslamate/db:/var/lib/postgresql
    networks:
      - npm

  teslamate-grafana:
    image: teslamate/grafana:3.0.0@sha256:e02d1f036dd10771ea04db2bafc483067a9dbb874d0b5137dda5a6fe539b77dc
    container_name: teslamate-grafana
    restart: unless-stopped
    #ports:
    #  - 3000:3000
    environment:
      - TZ=Europe/Amsterdam
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${TESLAMATE_DB_PASSWORD}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate-db
    volumes:
      - ${DOCKER_DATA_DIR}/teslamate/grafana:/var/lib/grafana
    depends_on:
      - teslamate-db
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.teslamate-grafana.rule=Host(`grafana-tesla.${DOMAIN}`)
      - traefik.http.routers.teslamate-grafana.entrypoints=websecure
      - traefik.http.routers.teslamate-grafana.tls=true
      - traefik.http.services.teslamate-grafana.loadbalancer.server.port=3000
    networks:
      - npm

  teslamate-mosquitto:
    image: eclipse-mosquitto:2.0.22@sha256:914f529386804c8278a4e581526b9be5e1604df44b30daabc70aa97dcefe5268
    container_name: teslamate-mosquitto
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ${DOCKER_DATA_DIR}/teslamate/mosquitto/config:/mosquitto/config
      - ${DOCKER_DATA_DIR}/teslamate/mosquitto/data:/mosquitto/data
    networks:
      - npm

networks:
  npm:
    external: true
