services:
  dockerproxy:
    image: linuxserver/socket-proxy:3.2.15@sha256:4e3ab628c94dfd58b5eef3847e1a0e42d8332c14983d391d585046037b373912
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
      - IMAGES=1
    #    ports:
    #      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      - npm
    read_only: true
    tmpfs:
      - /run
networks:
  npm:
    external: true