services:
  plexautolanguages:
    image: journeyover/plex-auto-languages:1.4.4@sha256:ee63eae3eb4add7381a1a3db926e4ba14625d2adfae0d6e93d92bb50f459afc5
    environment:
      - PLEX_URL=http://plex:32400
      - PLEX_TOKEN=${MY_PLEX_TOKEN}
      - NOTIFICATIONS_ENABLE=true
      - NOTIFICATIONS_APPRISE_CONFIGS=${APPRISE_CONFIGS_URLS}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/plexautolanguages/config:/config
    networks:
      - npm
    restart: unless-stopped
networks:
  npm:
    external: true
