services:
  plexautolanguages:
    image: journeyover/plex-auto-languages:1.5.4@sha256:50e8efa4e51ad7d6bf14e8905f344836e8beaccae5c44b8fb3404c0e2b6e9b00
    environment:
      - PLEX_URL=http://plex:32400
      - PLEX_TOKEN=${MY_PLEX_TOKEN}
      - NOTIFICATIONS_ENABLE=true
      - NOTIFICATIONS_APPRISE_CONFIGS=${APPRISE_CONFIGS_URLS}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/plexautolanguages/config:/config
    networks:
      - npm
    restart: unless-stopped
networks:
  npm:
    external: true
