services:
  plexautolanguages:
    image: journeyover/plex-auto-languages:1.5.2@sha256:43c7a77e1530cc87d78b7aa0e8ca66fb15b18caa97fe0e21f210137da267b192
    environment:
      - PLEX_URL=http://plex:32400
      - PLEX_TOKEN=${MY_PLEX_TOKEN}
      - NOTIFICATIONS_ENABLE=true
      - NOTIFICATIONS_APPRISE_CONFIGS=${APPRISE_CONFIGS_URLS}
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/plexautolanguages/config:/config
    networks:
      - npm
    restart: unless-stopped
networks:
  npm:
    external: true
