services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.8.8@sha256:b478adc66210c1effe147d3e4a0d8845c0418b136ca14c314b9d83a087ad1c1f
    container_name: openwebui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434   # resolves via Docker DNS on the npm network
      - WEBUI_AUTH=False                      # set True in prod
      # - DEFAULT_MODELS=llama3.1:8b
    volumes:
      - ${DOCKER_DATA_DIR}/openwebui/data:/app/backend/data
      # - ${MEDIA_DIR}/openwebui:/app/backend/data
    networks:
      - npm

networks:
  npm:
    external: true