services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.8.10@sha256:ee057955040ce91e3e787e4b7978c9c23e828972c68d01d787ed40f9a307df9f
    container_name: openwebui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434   # resolves via Docker DNS on the npm network
      - WEBUI_AUTH=False                      # set True in prod
      # - DEFAULT_MODELS=llama3.1:8b
    volumes:
      - ${DOCKER_DATA_DIR}/openwebui/data:/app/backend/data
      # - ${MEDIA_DIR}/openwebui:/app/backend/data
    networks:
      - npm

networks:
  npm:
    external: true