services:
  shelfmark:
    container_name: shelfmark
    image: ghcr.io/calibrain/shelfmark:v1.3.2@sha256:8700c1d3b6bb94e1b5f9482bac12e39652ed737de02f256920e1ad982a7ac0f1
    environment:
      UID: ${UID}
      GID: ${GID}
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      USE_BOOK_TITLE: true
      BOOK_LANGUAGE: nl
      USE_CF_BYPASS: true
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}/downloads/usenet/books:/books
      - ${DOCKER_DATA_DIR}/shelfmark/config:/config
    networks:
      - npm
    labels:
      - traefik.enable=true
      - traefik.http.routers.shelfmark.rule=Host(`shelfmark.${DOMAIN}`)
      - traefik.http.routers.shelfmark.entrypoints=websecure
      - traefik.http.routers.shelfmark.tls=true
      - traefik.http.services.shelfmark.loadbalancer.server.port=8084
networks:
  npm:
    external: true
