services:
  arl-sentinel:
    image: python:3.14-slim@sha256:44dd04494ee8f3b538294360e7c4b3acb87c8268e4d0a4828a6500b1eff50061
    container_name: arl-sentinel
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python sentinel.py"
    environment:
      - TZ=Europe/Amsterdam
      - CHECK_INTERVAL_SECONDS=21600
      - GOTIFY_URL=http://gotify
      - GOTIFY_TOKEN=${ARL_SENTINEL_GOTIFY_TOKEN}
      - DOCKERPROXY_URL=http://arl-dockerproxy:2375
      - ATTEMPT_AUTO_LOGIN=true
      - DEEZER_EMAIL=${DEEZER_EMAIL}
      - DEEZER_PASSWORD=${DEEZER_PASSWORD}
    volumes:
      - ${DOCKER_DATA_DIR}/arl-sentinel/app:/app
      - ${DOCKER_DATA_DIR}/arl-sentinel/data:/data
      - ${DOCKER_DATA_DIR}/arl-sentinel/inbox:/inbox
      - ${DOCKER_DATA_DIR}/deemix/config:/targets/deemix
      - ${DOCKER_DATA_DIR}/spotizerr/data/creds:/targets/spotizerr
    restart: unless-stopped
    depends_on:
      - arl-dockerproxy
    networks:
      - npm

  arl-dockerproxy:
    image: linuxserver/socket-proxy:3.4.1@sha256:6f2cce2d71ab810ddbab6ced411436ee7dcaaeaf223d47cb44450887adb54f40
    container_name: arl-dockerproxy
    environment:
      - CONTAINERS=1
      - POST=0
      - ALLOW_RESTARTS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - npm
    read_only: true
    tmpfs:
      - /run

networks:
  npm:
    external: true
