services:
  triliumnext:
    image: triliumnext/trilium:v0.102.2@sha256:f1a2fd88e7032d60f863231ce94348e906bcd6a5fa043801badd5896c20c064d
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    #    ports:
    #      - "8080:8080"
    volumes:
      - ${DOCKER_DATA_DIR}/triliumnext/config:/home/node/trilium-data
    networks:
      - npm
networks:
  npm:
    external: true