services:
  triliumnext:
    image: triliumnext/trilium:v0.102.0@sha256:ced97a926b6f3fcde86e26e4319b97686426cb4fc27e85c4fc35bf6150ce64f8
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    #    ports:
    #      - "8080:8080"
    volumes:
      - ${DOCKER_DATA_DIR}/triliumnext/config:/home/node/trilium-data
    networks:
      - npm
networks:
  npm:
    external: true