services:
  triliumnext:
    image: triliumnext/trilium:v0.104.0@sha256:8e053aa58a90c1690106a324a4692690ba0491c21ae40485b4051e2911df9489
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    #    ports:
    #      - "8080:8080"
    volumes:
      - ${DOCKER_DATA_DIR}/triliumnext/config:/home/node/trilium-data
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.triliumnext.rule=Host(`trilium.${DOMAIN}`)
      - traefik.http.routers.triliumnext.entrypoints=websecure
      - traefik.http.routers.triliumnext.tls=true
      - traefik.http.services.triliumnext.loadbalancer.server.port=8080
      - homepage.group=Media
      - homepage.name=Trilium
      - homepage.icon=trilium.png
      - homepage.href=https://trilium.${DOMAIN}/
      - homepage.description=Hierarchical note taking application with focus on building large personal knowledge bases
    networks:
      - npm
networks:
  npm:
    external: true