services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:2.8.8@sha256:3d62b8f8eece5fe947026ac3925ff08fda245b3d6ba2c3916b94da91e0010c74
    container_name: bentopdf
    restart: unless-stopped
#    ports:
#      - '3000:80'
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=BentoPDF
      - homepage.icon=sh-bentopdf-dark.png
      - homepage.href=http://pdf.${DOMAIN}/
      - homepage.description=A powerful, privacy-first, client-side PDF toolkit
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.bentopdf.rule=Host(`pdf.${DOMAIN}`)
      - traefik.http.routers.bentopdf.entrypoints=websecure
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
networks:
  npm:
    external: true