services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:2.8.2@sha256:d59a3812cb98c4887672ea73425722ee3dd7010969736c974c6b4ce7ba32c4fb
    container_name: bentopdf
    restart: unless-stopped
#    ports:
#      - '3000:80'
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=BentoPDF
      - homepage.icon=sh-bentopdf-dark.png
      - homepage.href=http://pdf.${DOMAIN}/
      - homepage.description=A powerful, privacy-first, client-side PDF toolkit
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.bentopdf.rule=Host(`pdf.${DOMAIN}`)
      - traefik.http.routers.bentopdf.entrypoints=websecure
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
networks:
  npm:
    external: true