services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:2.4.0@sha256:fc4f232dcf4343f33db6ed55646c35846d990df10144c25ef1b2c32847d6bd03
    container_name: bentopdf
    restart: unless-stopped
#    ports:
#      - '3000:80'
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=BentoPDF
      - homepage.icon=sh-bentopdf-dark.png
      - homepage.href=http://pdf.${DOMAIN}/
      - homepage.description=A powerful, privacy-first, client-side PDF toolkit
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.bentopdf.rule=Host(`pdf.${DOMAIN}`)
      - traefik.http.routers.bentopdf.entrypoints=websecure
      - traefik.http.routers.bentopdf.tls=true
      - traefik.http.services.bentopdf.loadbalancer.server.port=8080
networks:
  npm:
    external: true