networks:
  npm:
    external: true
  termix-net:
    driver: bridge

services:
  termix:
    image: ghcr.io/lukegus/termix:release-2.2.0@sha256:17e9a2c3f554227c03d5930db82f35ca0e3ad9dfea1377d64804df7cade69216
    container_name: termix
    restart: unless-stopped
    volumes:
      - termix-data:/app/data
    environment:
      PORT: '8080'
    depends_on:
      - guacd
    networks:
      - npm
      - termix-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.termix.rule=Host(`termix.${DOMAIN}`)
      - traefik.http.routers.termix.entrypoints=websecure
      - traefik.http.routers.termix.tls=true
      - traefik.http.services.termix.loadbalancer.server.port=8080
      - homepage.group=Tools
      - homepage.name=Termix
      - homepage.icon=termix.png
      - homepage.href=https://termix.${DOMAIN}/
      - homepage.description=Web-based terminal manager

  guacd:
    image: guacamole/guacd:1.6.0@sha256:8974eaa9ba32f713daf311e7cc8cd7e4cdfba1edea39eed75524e78ef4b08f4f
    container_name: guacd
    restart: unless-stopped
    networks:
      - termix-net

volumes:
  termix-data:
    driver: local
