services:
  gotify:
    #    ports:
    #      - 80:80
    volumes:
      - ${DOCKER_DATA_DIR}/gotify/config:/app/data
    container_name: gotify
    image: gotify/server:3.0.0@sha256:d75e89e0e28389c00c2556afe01282a37ee9756b0285799aa25214243aebd5e5
    environment:
      - GOTIFY_OIDC_ENABLED=${GOTIFY_OIDC_ENABLED}
      - GOTIFY_OIDC_ISSUER=${GOTIFY_OIDC_ISSUER}
      - GOTIFY_OIDC_CLIENTID=${GOTIFY_OIDC_CLIENTID}
      - GOTIFY_OIDC_CLIENTSECRET=${GOTIFY_OIDC_CLIENTSECRET}
      - GOTIFY_OIDC_REDIRECTURL=${GOTIFY_OIDC_REDIRECTURL}
      - GOTIFY_OIDC_AUTOREGISTER=${GOTIFY_OIDC_AUTOREGISTER}
      - GOTIFY_OIDC_USERNAMECLAIM=${GOTIFY_OIDC_USERNAMECLAIM}
      - GOTIFY_OIDC_LINK_BY_USERNAME=${GOTIFY_OIDC_LINK_BY_USERNAME}
      - GOTIFY_OIDC_SCOPES=${GOTIFY_OIDC_SCOPES}
    labels:
      - homepage.group=Infra
      - homepage.name=Gotify
      - homepage.icon=gotify.png
      - homepage.href=http://notifications.${DOMAIN}/
      - homepage.description=Notifications
      - homepage.widget.type=gotify
      - homepage.widget.url=http://gotify:80
      - homepage.widget.fields=["messages"]
      - homepage.widget.key=${GOTIFY_API}
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.gotify.rule=Host(`notifications.${DOMAIN}`)
      - traefik.http.routers.gotify.entrypoints=websecure
      - traefik.http.routers.gotify.tls=true
      - traefik.http.services.gotify.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true