{
 "title": "VictoriaMetrics - vmalert",
 "description": "Overview for VictoriaMetrics vmalert v1.117.0 or higher",
 "tags": [ "victoriametrics" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"^vmalert.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "file",
    "query": {
     "query": "label_values(vmalert_iteration_total{job=~\"$job\", instance=~\"$instance\"},file)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(vmalert_iteration_total{job=~\"$job\", instance=~\"$instance\"}, group)"
    }
   },
   { "name": "topk", "query": "5, 10, 20, 30, 40, 50" },
   { "name": "filter" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Config update",
   "type": "stat",
   "description": "Shows if the last configuration update was successful. \"Not Ok\" means there was an unsuccessful attempt to update the configuration due to some error. Check the log for details.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vmalert_config_last_reload_successful{job=~\"$job\", instance=~\"$instance\"} < 1 )"
    }
   ]
  },
  {
   "title": "Alerting rules",
   "type": "stat",
   "description": "Shows the total number of loaded alerting rules across selected instances and groups.",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vmalert_alerting_rules_last_evaluation_samples{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"})"
    }
   ]
  },
  {
   "title": "Recording rules",
   "type": "stat",
   "description": "Shows the total number of loaded recording rules across selected instances and groups.",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vmalert_recording_rules_last_evaluation_samples{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Shows the total number of errors generated by recording/alerting rules for selected instances and groups.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(increase(vmalert_alerting_rules_errors_total{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}[$__rate_interval]))) + \n(sum(increase(vmalert_recording_rules_errors_total{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "No data errors",
   "type": "stat",
   "description": "Shows number of Recording Rules which produce no data.\n\n Usually it means that such rules are misconfigured, since they give no output during the evaluation.\nPlease check if rule's expression is correct and it is working as expected.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vmalert_recording_rules_last_evaluation_samples{job=~\"$job\", instance=~\"$instance\"} < 1)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(job, version) (label_replace(vm_app_version{job=~\"$job\", instance=~\"$instance\", short_version!=\"\"}, \"version\", \"$1\", \"short_version\", \"(.*)\") or vm_app_version{job=~\"$job\", instance=~\"$instance\", short_version=\"\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(min_over_time(up{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Overview ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Alerts fired total ($instance)",
   "type": "timeseries",
   "description": "Shows the number of fired alerts by job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vmalert_alerts_fired_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Top $topk groups avg evaluation duration ($group)",
   "type": "timeseries",
   "description": "Top $topk groups by evaluation duration. Shows groups that take the most of time during the evaluation across all instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($topk, max(sum(\n    rate(vmalert_iteration_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])\n/\n    rate(vmalert_iteration_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])\n) by(job, instance, group, file)) \nby(job, group, file))",
     "legendFormat": "({{job}}) {{group}}({{file}})"
    }
   ]
  },
  {
   "title": "Rules execution rate ($instance)",
   "type": "timeseries",
   "description": "Shows how many requests (executions) per second vmalert sends to the configured datasource.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vmalert_execution_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rules execution errors ($instance)",
   "type": "timeseries",
   "description": "Shows the error rate while executing configured rules. Non-zero value means there are some issues with existing rules. Check the logs to get more details.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vmalert_execution_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage % ($instance)",
     "type": "timeseries",
     "description": "How much resident memory (RAM) the process is actually using, compared to its allowed container or system limit.\n\n- Good: Below 70% most of the time, maybe spiking a bit under load.\n- Bad: Above 90% for more than 5 minutes = risk of out-of-memory (OOM) kill.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage %($instance)",
     "type": "timeseries",
     "description": "Shows the CPU usage percentage per vmalert instance. \nIf you think that usage is abnormal or unexpected pls file an issue and attach CPU profile if possible.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n  rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) \n  / \n  process_cpu_cores_available{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RSS anonymous memory % usage",
     "type": "timeseries",
     "description": "Share for memory allocated by the process itself. When memory usage reaches 100% it will be likely OOM-killed.\nSafe memory usage % considered to be below 80%",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_anon_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage ($instance)",
     "type": "timeseries",
     "description": "Shows the max number of CPU cores used  by a `job` and the corresponding limit.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "min(process_cpu_cores_available{job=~\"$job\", instance=~\"$instance\"}) by(job)",
       "legendFormat": "limit ({{job}})"
      }
     ]
    },
    {
     "title": "Memory usage ($instance)",
     "type": "timeseries",
     "description": "Amount of used RSS memory\n\nIf you think that usage is abnormal or unexpected, please file an issue and attach memory profile if possible.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "CPU pressure",
     "type": "timeseries",
     "description": "CPU pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\n\n**Lower is better.**\n\nPressure is measured as amount of time within 1sec time window the process was:\n- waiting: at least one task in the process was ready to run (runnable) but couldn't get scheduled on the CPU.\n- stalled: all tasks in the process (except idle ones) were unable to get CPU time — a full CPU stall.\n\nIf there's a CPU burst, it's normal to see waiting or stalled > 100ms. It only becomes a concern if it consistently climbs above 50-100ms and aligns with latency spikes or GC slowdowns.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_pressure_cpu_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - waiting"
      },
      {
       "expr": "sum(rate(process_pressure_cpu_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - stalled"
      }
     ]
    },
    {
     "title": "Memory pressure",
     "type": "timeseries",
     "description": "Shows memory pressure based on [Pressure Stall Information](https://docs.kernel.org/accounting/psi.html).\n\n**Lower is better.**\n\nPressure is measured as amount of time within 1sec time window the process was:\n- waiting: at least one thread was blocked on memory.\n- stalled: every thread was blocked on memory (severe pressure).\n\nElevated memory pressure can slowdown the process performance by utilizing more disk IO. Consider increasing amount of available RAM limit or decreasing the load on the process.\n\nSee major page faults rate panel in Troubleshooting section if this metric continued to be high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_pressure_memory_waiting_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - waiting"
      },
      {
       "expr": "sum(rate(process_pressure_memory_stalled_seconds_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "{{instance}} - stalled"
      }
     ]
    },
    {
     "title": "Goroutines ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(go_goroutines{job=~\"$job\", instance=~\"$instance\"}) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Open FDs usage % ($instance)",
     "type": "timeseries",
     "description": "Panel shows the percentage of open file descriptors in the OS.\nReaching the limit of open files can cause various issues and must be prevented.\n\nSee how to change limits here https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(process_open_fds{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    process_max_fds{job=~\"$job\", instance=~\"$instance\"}\n) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go scheduling latency",
     "type": "timeseries",
     "description": "Shows the time goroutines have spent in runnable state before actually running.\n\n**Lower is better.**\n\nHigh values or values exceeding the threshold is usually a sign of            insufficient CPU resources or CPU throttling. \n\nVerify that service has enough CPU resources. Otherwise, the service could work unreliably with delays in processing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{job=~\"$job\"}[$__rate_interval])) by (job, instance, le))) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU spent on GC ($instance)",
     "type": "timeseries",
     "description": "Shows the percent of CPU spent on garbage collection.\n\nIf % is high, then CPU usage can be decreased by changing GOGC to higher values. Increasing GOGC value will increase memory usage, and decrease CPU usage.\n\nTry searching for keyword `GOGC` at https://docs.victoriametrics.com/victoriametrics/troubleshooting/ ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n  rate(go_gc_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) \n / rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n ) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory allocations rate",
     "type": "timeseries",
     "description": "Shows the rate of allocations in memory. Sudden increase in allocations would mean increased pressure on Go Garbage Collector and can saturate CPU resources of the application.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[$__rate_interval])) by (job, instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-default flags",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 345 },
     "targets": [
      {
       "expr": "sum(flag{is_set=\"true\", job=~\"$job\", instance=~\"$instance\"}) by(job, instance, name, value)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Missed evaluations ($instance)",
     "type": "timeseries",
     "description": "Missed evaluation means that group evaluation time takes longer than the configured evaluation interval. \nThis may result in missed alerting notifications or recording rules samples. Try increasing evaluation interval or concurrency for such groups. See https://docs.victoriametrics.com/victoriametrics/vmalert/#groups\n\nIf rule expressions are taking longer than expected, please see https://docs.victoriametrics.com/victoriametrics/troubleshooting/#slow-queries.\"",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 345 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vmalert_iteration_missed_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job, group, file) > 0",
       "legendFormat": "({{job}}) {{group}}({{file}})"
      }
     ]
    },
    {
     "title": "Restarts ($job)",
     "type": "timeseries",
     "description": "Shows the number of restarts per job. The chart can be useful to identify periodic process restarts and correlate them with potential issues or anomalies. Normally, processes shouldn't restart unless restart was inited by user. The reason of restarts should be figured out by checking the logs of each specific service. ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(changes(vm_app_start_timestamp{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) > 0) by(job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Group Iteration Reset ($instance)",
     "type": "timeseries",
     "description": "Group iteration reset can be caused by irregular delays during evaluation or by the system wall clock being moved backward.\nIf it is caused by host clock changes, vmalert could generate duplicate results for the group rules, since some evaluations could be repeated.\nCheck the host clock time synchronization configuration if this happens frequently.\n",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vmalert_iteration_reset_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job, group, file) > 0",
       "legendFormat": "({{job}}) {{group}}({{file}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerting rules ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topk active alerts ($group)",
     "type": "timeseries",
     "description": "Shows top $topk current active (firing) alerting rules.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 370 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, sum(vmalert_alerts_firing{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}) by(job, group, file, alertname) > 0)",
       "legendFormat": "({{job}}) {{group}}.{{alertname}}({{file}})"
      }
     ]
    },
    {
     "title": "Errors ($group)",
     "type": "timeseries",
     "description": "Shows the events when rule execution resulted into an error. Check the logs for more details.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 370 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vmalert_alerting_rules_errors_total{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])) by(job, group, file, alertname) > 0",
       "legendFormat": "({{job}}) {{group}}.{{alertname}}({{file}})"
      }
     ]
    },
    {
     "title": "Pending ($group)",
     "type": "timeseries",
     "description": "Shows the current pending alerting rules per group.\nBy pending means the rule which remains active less than configured `for` parameter.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vmalert_alerts_pending{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}) by(job, group, file, alertname) > 0",
       "legendFormat": "({{job}}) {{group}}.{{alertname}}({{file}})"
      }
     ]
    },
    {
     "title": "Errors rate to Alertmanager",
     "type": "timeseries",
     "description": "Shows the error rate for the attempts to send alerts to Alertmanager. If not zero it means there issues on attempt to send notification to Alertmanager and some alerts may be not delivered properly. Check the logs for more details.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 378 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vmalert_alerts_send_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(instance, addr) > 0",
       "legendFormat": "{{instance}} => {{addr}}"
      }
     ]
    },
    {
     "title": "Requests rate to Alertmanager by job ($group)",
     "type": "timeseries",
     "description": "Shows how many alerts are sent to Alertmanager per second. Only active alerts are sent.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 386 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vmalert_alerts_sent_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job, addr) > 0",
       "legendFormat": "{{job}} => {{addr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Recording rules ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $topk rules by produced samples ($group)",
     "type": "timeseries",
     "description": "Shows the top $topk recording rules which generate the most of [samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples). Each generated sample is basically a time series which then ingested into configured remote storage. Rules with high numbers may cause the most pressure on the remote database and become a source of too high cardinality.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 385 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk($topk, \n  max(\n    sum(vmalert_recording_rules_last_evaluation_samples{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}) by(job, instance, group, file, recording) > 0\n  ) by(job, group, file, recording)\n)",
       "legendFormat": "({{job}}) {{group}}.{{recording}}({{file}})"
      }
     ]
    },
    {
     "title": "Rules with 0 produced samples ($group)",
     "type": "timeseries",
     "description": "Shows the rules which do not produce any [samples](https://docs.victoriametrics.com/victoriametrics/keyconcepts/#raw-samples) during the evaluation. Usually it means that such rules are misconfigured, since they give no output during the evaluation.\nPlease check if rule's expression is correct and it is working as expected.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 385 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(vmalert_recording_rules_last_evaluation_samples{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"} < 1) by(job, group, file, recording)",
       "legendFormat": "({{job}}) {{group}}.{{recording}}({{file}})"
      }
     ]
    },
    {
     "title": "Errors ($group)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 393 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vmalert_recording_rules_errors_total{job=~\"$job\", instance=~\"$instance\", group=~\"$group\", file=~\"$file\"}[$__rate_interval])) by(job, group, file, recording) > 0",
       "legendFormat": "({{job}}) {{group}}.{{recording}}({{file}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datapoints send rate ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(rate(vmalert_remotewrite_sent_rows_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) default sum(rate(vmalert_remotewrite_sent_rows_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes write rate ($instance)",
     "type": "timeseries",
     "description": "Shows the global rate for number of written bytes via remote write connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(vmalert_remotewrite_conn_bytes_written_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Datapoints drop rate ($instance)",
     "type": "timeseries",
     "description": "Data could be dropped in two scenarios:\n1. The remote write queue(configured by -remoteWrite.maxQueueSize) is full:  \nThe queue can fill rapidly if heavy rules generate millions of series, or if remote write requests are unable to send data to the destination in a timely manner, resulting in data being jammed in the queue. Consider tuning -remoteWrite.maxQueueSize or -remoteWrite.concurrency.\nSee also Rows per request pannel.\n2. The request to the configured remote write URL failed(vmalert performs up to 5 retries before dropping the data).\n\nCheck vmalert's error logs for the specific error message.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(rate(vmalert_remotewrite_dropped_rows_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remote write queue size ($instance)",
     "type": "timeseries",
     "description": "Displays the maximum 99th percentile of the number of time series pending in the remote write queue.\n\nThe maximum queue size is configured by remoteWrite.maxQueueSize. \nvmalert will begin dropping data if the queue has no room for newly generated data.\nThe queue can fill rapidly when heavy rules generate millions of series, or when remote write requests are unable to send data to the destination in a timely manner, causing data to accumulate in the queue. Consider tuning -remoteWrite.maxQueueSize or -remoteWrite.concurrency.\n\nSee also the Rows per request panel.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, sum(increase(vmalert_remotewrite_queue_size_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, vmrange))) > 1",
       "legendFormat": "current"
      },
      {
       "expr": "min(vmalert_remotewrite_queue_capacity{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Rows per request ($instance)",
     "type": "timeseries",
     "description": "Displays the maximum 99th percentile of the number of data samples sent per request to the configured remote write URL.\nThe value is influenced by the utilization of the remote write queue. It is normal for this metric to remain low when there are no rules generating a large number of series, and to spike when heavy rules generate thousands of series.\nDuring periods of high load (when many heavy rules are generating results), the optimal value for rows per request should be high to maximize the efficiency of each push operation.\n\nIf you observe datapoint drops and consistently low values for rows per request, try checking the write latency between vmalert and the remote write destination, or increasing `-remoteWrite.flushInterval`.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "max(histogram_quantile(0.99, sum(increase(vmalert_remotewrite_sent_rows_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, vmrange)))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Connections ($instance)",
     "type": "timeseries",
     "description": "Shows current number of established connections to remote write endpoints.\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(max_over_time(vmalert_remotewrite_conns{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}