services:
  grafana:
    image: grafana/grafana:13.2.0@sha256:3fd54ae1214669f8355f065ec9f6445d5279a3d77095ab048ca045685272429b
    container_name: grafana
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
    volumes:
      - ${DOCKER_DATA_DIR}/grafana/data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    labels:
      - homepage.group=Infra
      - homepage.name=Grafana
      - homepage.icon=grafana.png
      - homepage.href=https://grafana.${DOMAIN}/
      - homepage.description=Dashboards
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - npm

networks:
  npm:
    external: true
