services:
  nextcloud:
    image: linuxserver/nextcloud:34.0.1@sha256:397d5e5bdf1d626ab3f160575f6b8415b6479f5f258607c902385e48c92f2045
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextclouddb
      - nextcloud-redis
    volumes:
      - ${DOCKER_DATA_DIR}/nextcloud/config:/config
      - ${MEDIA_DIR}/nextcloud:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=nextcloud-redis
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=Nextcloud
      - homepage.icon=nextcloud.png
      - homepage.href=http://nextcloud.${DOMAIN}/
      - homepage.description=Open source content collaboration platform
      - homepage.widget.type=nextcloud
      - homepage.widget.fields=["freespace", "numfiles"]
      - homepage.widget.url=https://nextcloud:443
      - homepage.widget.key=${NEXTCLOUD_WIDGET_KEY}
  nextclouddb:
    image: linuxserver/mariadb:11.8.8@sha256:5381fd649df2d8424f744ed703c33c40cfb077187a123a37238d30f2bd80ce8a
    container_name: nextclouddb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    volumes:
      - ${DOCKER_DATA_DIR}/nextclouddb/config:/config
    restart: unless-stopped
    networks:
      - npm
  nextcloud-redis:
    image: redis:8.8.0-alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - npm
  collabora:
    container_name: collabora
    image: collabora/code:26.04.2.2.1@sha256:f8a308bcd12ad09babcd635662b512776b0749fc04c9a63db568865bd195b4d9
    restart: unless-stopped
    command:
      - --o:ssl.enable=false
      - --o:ssl.termination=true
    cap_add:
      - MKNOD
    environment:
      - domain=nextcloud\.${DOMAIN}
      - username=${COLLABORA_ADMIN_USER}
      - password=${COLLABORA_ADMIN_PASSWORD}
    networks:
      - npm
    labels:
      - traefik.enable=true
      - traefik.http.routers.collabora.rule=Host(`collabora.${DOMAIN}`)
      - traefik.http.routers.collabora.entrypoints=websecure
      - traefik.http.routers.collabora.tls=true
      - traefik.http.services.collabora.loadbalancer.server.port=9980
networks:
  npm:
    external: true