services:
  nextcloud:
    image: linuxserver/nextcloud:33.0.2@sha256:b06a868994d366aff8cc69851f478a6f235134971d50fd44936c60937c64a15e
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextclouddb
      - nextcloud-redis
    volumes:
      - ${DOCKER_DATA_DIR}/nextcloud/config:/config
      - ${MEDIA_DIR}/nextcloud:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=nextcloud-redis
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=Nextcloud
      - homepage.icon=nextcloud.png
      - homepage.href=http://nextcloud.${DOMAIN}/
      - homepage.description=Open source content collaboration platform
      - homepage.widget.type=nextcloud
      - homepage.widget.fields=["freespace", "numfiles"]
      - homepage.widget.url=https://nextcloud:443
      - homepage.widget.key=${NEXTCLOUD_WIDGET_KEY}
  nextclouddb:
    image: linuxserver/mariadb:11.4.10@sha256:c45132cefda1fc6e2034539631fa769070f37d9f673100dba7c0f7077c2e8b8c
    container_name: nextclouddb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    volumes:
      - ${DOCKER_DATA_DIR}/nextclouddb/config:/config
    restart: unless-stopped
    networks:
      - npm
  nextcloud-redis:
    image: redis:8.6.2-alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - npm
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:9.3.1@sha256:53a06109f1f4029a78f913a061e14f01bff023d109024073a13d4416b54d2195
    restart: unless-stopped
    environment:
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    expose:
      - '80'
      - '443'
    networks:
      - npm
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    labels:
      - traefik.enable=true
      - traefik.http.routers.documentserver.rule=Host(`documentserver.${DOMAIN}`)
      - traefik.http.routers.documentserver.entrypoints=websecure
      - traefik.http.routers.documentserver.tls=true
      - traefik.http.services.documentserver.loadbalancer.server.port=80
      - traefik.http.middlewares.documentserver-forward.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.documentserver-forward.headers.customRequestHeaders.X-Forwarded-Host={host}
      - traefik.http.routers.documentserver.middlewares=documentserver-forward
networks:
  npm:
    external: true
volumes:
  document_data:
  document_log: