services:
  nextcloud:
    image: linuxserver/nextcloud:33.0.5@sha256:4de5f8f400f06690751c2f1a07d8bedb3eec084351e24f5ba074198da080be1c
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextclouddb
      - nextcloud-redis
    volumes:
      - ${DOCKER_DATA_DIR}/nextcloud/config:/config
      - ${MEDIA_DIR}/nextcloud:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=nextcloud-redis
    networks:
      - npm
    labels:
      - homepage.group=Media
      - homepage.name=Nextcloud
      - homepage.icon=nextcloud.png
      - homepage.href=http://nextcloud.${DOMAIN}/
      - homepage.description=Open source content collaboration platform
      - homepage.widget.type=nextcloud
      - homepage.widget.fields=["freespace", "numfiles"]
      - homepage.widget.url=https://nextcloud:443
      - homepage.widget.key=${NEXTCLOUD_WIDGET_KEY}
  nextclouddb:
    image: linuxserver/mariadb:11.4.12@sha256:adbb0142f55abd0e913b8fdd017f637d2318d434e74755908c768399e96403ec
    container_name: nextclouddb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    volumes:
      - ${DOCKER_DATA_DIR}/nextclouddb/config:/config
    restart: unless-stopped
    networks:
      - npm
  nextcloud-redis:
    image: redis:8.8.0-alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - npm
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:9.4.0@sha256:e3da62a847b9a5d51a11f73cfea1d9c13c3be3809614490d4edddcf01dcf919b
    restart: unless-stopped
    environment:
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    expose:
      - '80'
      - '443'
    networks:
      - npm
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    labels:
      - traefik.enable=true
      - traefik.http.routers.documentserver.rule=Host(`documentserver.${DOMAIN}`)
      - traefik.http.routers.documentserver.entrypoints=websecure
      - traefik.http.routers.documentserver.tls=true
      - traefik.http.services.documentserver.loadbalancer.server.port=80
      - traefik.http.middlewares.documentserver-forward.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.documentserver-forward.headers.customRequestHeaders.X-Forwarded-Host={host}
      - traefik.http.routers.documentserver.middlewares=documentserver-forward
networks:
  npm:
    external: true
volumes:
  document_data:
  document_log: