services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.2@sha256:ea801368eac6b1f0d08ad35dabcbbd0a91147a49ba9761df84b2e047532d74e5
    container_name: homepage
    volumes:
      - ${DOCKER_DATA_DIR}/homepage/config:/app/config
    networks:
      - npm
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=3000
networks:
  npm:
    external: true
