services:
  homepage:
    image: docker.io/gethomepage/homepage:v2.4.0@sha256:643bd0be730d40f69d58028a55d1a896739333e8815786df42bc97f109ecbe61
    container_name: homepage
    volumes:
      - ${DOCKER_DATA_DIR}/homepage/config:/app/config
    networks:
      - npm
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - HOMEPAGE_ALLOWED_HOSTS=${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.middlewares=authentik-forwardauth@docker
      - traefik.http.services.homepage.loadbalancer.server.port=3000
networks:
  npm:
    external: true
