services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:149.0.7808.0@sha256:78109ccd8701fee19917ab416cf2b5ecc19042aa5298a840c137f83734e32883
    restart: unless-stopped
    command:
      - --remote-allow-origins=*
    networks:
      - npm
networks:
  npm:
    external: true