services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:148.0.7766.3@sha256:cd9721a605bf65a8a9085cb605959e826b7120496a19d83f9f23472370026f40
    restart: unless-stopped
    command:
      - --remote-allow-origins=*
    networks:
      - npm
networks:
  npm:
    external: true