services:
  headless-chrome:
    #ports:
    #   - 9222:9222
    container_name: headless-chrome
    image: chromedp/headless-shell:147.0.7727.3@sha256:69d7fb1053f0ad3dc49f3369fc99bebc7575de228a6b143e6fd99b38a9579716
    restart: unless-stopped
    command:
      - --remote-allow-origins=*
    networks:
      - npm
networks:
  npm:
    external: true