services:
  byparr:
    image: ghcr.io/thephaseless/byparr:3.0.1@sha256:ee50262bc83d21c364863948436a3e7444553331157a93444477e9f067de210e 
    container_name: byparr
    init: true
    restart: unless-stopped
    shm_size: 2gb
    networks:
      - npm
networks:
  npm:
    external: true