services:
  byparr:
    image: ghcr.io/thephaseless/byparr:3.0.0@sha256:b44c612ef598e593346852a9a9ce92b8789e9ac8080544bdd38e125b99a2ee69 
    container_name: byparr
    init: true
    restart: unless-stopped
    shm_size: 2gb
    networks:
      - npm
networks:
  npm:
    external: true