services:
  byparr:
    image: ghcr.io/thephaseless/byparr:3.0.3@sha256:db931cd7b7880a454bf7d12640155dbb57386088629811ecf452f7626be49e3c 
    container_name: byparr
    init: true
    restart: unless-stopped
    shm_size: 2gb
    networks:
      - npm
networks:
  npm:
    external: true