services:
  cloudflared:
    container_name: cloudflared
    environment:
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=14333
    volumes:
      - ${DOCKER_DATA_DIR}/cloudflared/config:/config
    networks:
      - npm
    restart: unless-stopped
    image: wisdomsky/cloudflared-web:2026.9.0@sha256:3e0ab32c5a24c6a555e6b1f9ea80a0c4699e40e24b1ff8e943967c6b2008817e
    labels:
      - homepage.group=Infra
      - homepage.name=Cloudflared
      - homepage.icon=cloudflare.png
      - homepage.href=https://cloudflared.${DOMAIN}/
      - homepage.description=Tunnel to Cloudflare for public access
      - homepage.widget.type=cloudflared
      - homepage.widget.accountid=${ACCOUNTID}
      - homepage.widget.tunnelid=${TUNNELID}
      - homepage.widget.key=${CLOUDFLAREAPITOKEN}
      - traefik.enable=true
      - traefik.http.routers.cloudflared.rule=Host(`cloudflared.${DOMAIN}`)
      - traefik.http.routers.cloudflared.entrypoints=websecure
      - traefik.http.routers.cloudflared.tls=true
      - traefik.http.routers.cloudflared.middlewares=authentik-forwardauth@docker
      - traefik.http.services.cloudflared.loadbalancer.server.port=14333
networks:
  npm:
    external: true