services:
  cloudflared:
    container_name: cloudflared
    environment:
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=14333
    volumes:
      - ${DOCKER_DATA_DIR}/cloudflared/config:/config
    networks:
      - npm
    restart: unless-stopped
    image: wisdomsky/cloudflared-web:2026.3.0@sha256:102d02a0dce9db56aa80e6242c0f7f288e00410b103bf5a7f8c82f2e31464010
    labels:
      - homepage.group=Infra
      - homepage.name=Cloudflared
      - homepage.icon=cloudflare.png
      - homepage.href=https://cloudflared.${DOMAIN}/
      - homepage.description=Tunnel to Cloudflare for public access
      - homepage.widget.type=cloudflared
      - homepage.widget.accountid=${ACCOUNTID}
      - homepage.widget.tunnelid=${TUNNELID}
      - homepage.widget.key=${CLOUDFLAREAPITOKEN}
      - traefik.enable=true
      - traefik.http.routers.cloudflared.rule=Host(`cloudflared.${DOMAIN}`)
      - traefik.http.routers.cloudflared.entrypoints=websecure
      - traefik.http.routers.cloudflared.tls=true
      - traefik.http.routers.cloudflared.middlewares=authentik-forwardauth@docker
      - traefik.http.services.cloudflared.loadbalancer.server.port=14333
networks:
  npm:
    external: true