services:
  papra:
    image: ghcr.io/papra-hq/papra:latest@sha256:f6710d1064a200a79ff6c5499e9ce08581db4013879d70ba46bffdb27def2c3e
    container_name: papra
    restart: unless-stopped
#    ports:
#      - 1221:1221
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - APP_BASE_URL=https://papra.${DOMAIN}
    volumes:
      - ${DOCKER_DATA_DIR}/papra/config:/app/app-data
    user: ${PUID}:${PGID}
    networks:
      - npm
networks:
  npm:
    external: true