services:
  papra:
    image: ghcr.io/papra-hq/papra:latest@sha256:b6c5b1db64234f301575ea0ff0729361be6c9147767db72d65bcd6b6cd8088cb
    container_name: papra
    restart: unless-stopped
#    ports:
#      - 1221:1221
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - APP_BASE_URL=https://papra.${DOMAIN}
    volumes:
      - ${DOCKER_DATA_DIR}/papra/config:/app/app-data
    user: ${PUID}:${PGID}
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.papra.rule=Host(`papra.${DOMAIN}`)
      - traefik.http.routers.papra.entrypoints=websecure
      - traefik.http.routers.papra.tls=true
      - traefik.http.services.papra.loadbalancer.server.port=1221
    networks:
      - npm
networks:
  npm:
    external: true