services:
  quickstart:
    image: kometateam/quickstart:v0.9.12@sha256:7334b473393f7a60b9c1cfba3231b711a5d10cc8ea16a7a01866f26e8a95eea9
    container_name: quickstart
#    ports:
#      - 7171:7171
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/quickstart/config:/config
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true