services:
  quickstart:
    image: kometateam/quickstart:v0.10.11@sha256:f7caa5c2921dd55358d9d91bf18f9d422b4d9c752aa808ae49575ccdf6ba08b8
    container_name: quickstart
#    ports:
#      - 7171:7171
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/quickstart/config:/config
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true