services:
  quickstart:
    image: kometateam/quickstart:v0.10.0@sha256:195f48d3bfc8dbacf10072656c9a19b2a34f060426238dca1df516c64ea6818c
    container_name: quickstart
#    ports:
#      - 7171:7171
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ${DOCKER_DATA_DIR}/quickstart/config:/config
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true