services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:0.8.4@sha256:840c8f8da77f366a0b658661913352b860e5388d009ca4925f560ea6d200ffe5
#    ports:
#      - 5101:5101
    volumes:
      - ${MEDIA_DIR}/retro/roms:/app/library:ro
      - ${DOCKER_DATA_DIR}/retrom/config:/app/config
      - ${DOCKER_DATA_DIR}/retrom/data:/app/data/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true