services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:0.8.0@sha256:f5cc9732248e0e2ba6f2d81641c3152938b5c94d0c3089a1c9dfa48addb249de
#    ports:
#      - 5101:5101
    volumes:
      - ${MEDIA_DIR}/retro/roms:/app/library:ro
      - ${DOCKER_DATA_DIR}/retrom/config:/app/config
      - ${DOCKER_DATA_DIR}/retrom/data:/app/data/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true