services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:0.7.55@sha256:c0f0f721c5c8ed5918d4b06cf5c2bb2b130eb019db3468d12999c5da1ec0c164
#    ports:
#      - 5101:5101
    volumes:
      - ${MEDIA_DIR}/retro/roms:/app/library:ro
      - ${DOCKER_DATA_DIR}/retrom/config:/app/config
      - ${DOCKER_DATA_DIR}/retrom/data:/app/data/
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true