services:
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:2.2.0@sha256:ddcdd0f340043c2ec0a85ca74b9a6be9be42b1c0288c75fc36a26a43f695860b
    container_name: profilarr
    volumes:
      - ${DOCKER_DATA_DIR}/profilarr/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ORIGIN=https://profilarr.${DOMAIN}
      - PARSER_HOST=profilarr-parser
      - PARSER_PORT=5000
    depends_on:
      profilarr-parser:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - npm
    labels:
      - homepage.group=Media Management
      - homepage.name=Profilarr
      - homepage.id=colsmall
      - homepage.icon=https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f4d2.png
      - homepage.href=https://profilarr.${DOMAIN}/
      - homepage.description=Config management for -arr suite
      - traefik.enable=true
      - traefik.http.routers.profilarr.rule=Host(`profilarr.${DOMAIN}`)
      - traefik.http.routers.profilarr.entrypoints=websecure
      - traefik.http.routers.profilarr.tls=true
      - traefik.http.services.profilarr.loadbalancer.server.port=6868

  profilarr-parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:2.2.0@sha256:3cd3f8c4979ee66304a518462cc6c5b59825bae6b25e7dfa51b30178b9265df7
    container_name: profilarr-parser
    environment:
      - TZ=${TZ}
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - npm
    labels:
      - traefik.enable=false

networks:
  npm:
    external: true
