services:
  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:2.1.0@sha256:75a43c9c19c70f6e48315d4ed5cef3232d905da8fab397391a2078a5e0fd7ec1
    container_name: profilarr
    volumes:
      - ${DOCKER_DATA_DIR}/profilarr/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ORIGIN=https://profilarr.${DOMAIN}
      - PARSER_HOST=profilarr-parser
      - PARSER_PORT=5000
    depends_on:
      profilarr-parser:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - npm
    labels:
      - homepage.group=Media Management
      - homepage.name=Profilarr
      - homepage.id=colsmall
      - homepage.icon=https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/72x72/1f4d2.png
      - homepage.href=https://profilarr.${DOMAIN}/
      - homepage.description=Config management for -arr suite
      - traefik.enable=true
      - traefik.http.routers.profilarr.rule=Host(`profilarr.${DOMAIN}`)
      - traefik.http.routers.profilarr.entrypoints=websecure
      - traefik.http.routers.profilarr.tls=true
      - traefik.http.services.profilarr.loadbalancer.server.port=6868

  profilarr-parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:2.1.0@sha256:83d668258b2a798adaf25dec0d78e5159953c3b015e2d31edb8e5b9859f3c591
    container_name: profilarr-parser
    environment:
      - TZ=${TZ}
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - npm
    labels:
      - traefik.enable=false

networks:
  npm:
    external: true
