services:
  borg-ui:
    image: ainullcode/borg-ui:2.0.5@sha256:867c73983e5bef5491cdee1c34acf85fe8a9fe4f6ad5a9381e7ca2c382359ce6
    container_name: borg-web-ui
    restart: unless-stopped
    #ports:
    #  - "8081:8081"
    volumes:
      - ${DOCKER_DATA_DIR}/borg-ui/data:/data
      - ${DOCKER_DATA_DIR}/borg-ui/cache:/home/borg/.cache/borg
      - ${MEDIA_DIR}/nextcloud:/local:rw
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - REDIS_HOST=borg-redis
      - REDIS_PORT=6379
    depends_on:
      borg-redis:
        condition: service_healthy
    labels:
      - homepage.group=Infra
      - homepage.name=Borg UI
      - homepage.icon=borgbackup.png
      - homepage.href=http://borg.${DOMAIN}/
      - homepage.description=BorgBackup web interface
      - traefik.enable=true
      - traefik.http.routers.borg-ui.rule=Host(`borg.${DOMAIN}`)
      - traefik.http.routers.borg-ui.entrypoints=websecure
      - traefik.http.routers.borg-ui.tls=true
      - traefik.http.services.borg-ui.loadbalancer.server.port=8081
    networks:
      - npm

  borg-redis:
    image: redis:8.6.2-alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17
    container_name: borg-redis
    restart: unless-stopped
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - npm

networks:
  npm:
    external: true
