services:
  slskd:
    image: slskd/slskd:0.25.0@sha256:6a91991c05b7cbbe4e3dcc1f5e10f88d00a68f7ad2ef8a820b79496441b9b78c
    container_name: slskd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ${DOCKER_DATA_DIR}/slskd:/app
      - ${MEDIA_DIR}/downloads/slskd:/media/downloads/slskd
      - ${MEDIA_DIR}/music:/music:ro
    ports:
      - 50300:50300
#      - 5030:5030
#      - 5031:5031
    labels:
      - homepage.group=Media
      - homepage.name=Slskd
      - homepage.icon=slskd.png
      - homepage.href=http://slskd.${DOMAIN}/
      - homepage.description=Soulseek client
      - homepage.widget.type=slskd
      - homepage.widget.url=${SLSKD_INTERNAL_URL}
      - homepage.widget.key=${SLSKD_API}
      - homepage.widget.version=2
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.slskd.rule=Host(`slskd.${DOMAIN}`)
      - traefik.http.routers.slskd.entrypoints=websecure
      - traefik.http.routers.slskd.tls=true
      - traefik.http.services.slskd.loadbalancer.server.port=5030
    restart: unless-stopped
#    user: 568:568
    networks:
      my-macvlan-net:
        ipv4_address: ${SLSKD_IP}
      npm: null
networks:
  npm:
    external: true
  my-macvlan-net:
    external: true
