services:
  ollama:
    image: ollama/ollama:0.18.1@sha256:5949ec041e62b28f92d5ff1d7c34080ec67efd73ad24a523e2ff558a24f33072
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ${DOCKER_DATA_DIR}/ollama:/root/.ollama
    networks:
      - npm

    # --- OPTIONAL: NVIDIA GPU ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: 1

networks:
  npm:
    external: true