services:
  cloudcmd:
    container_name: cloudcmd
    volumes:
      - ${MEDIA_DIR}:/media
      - ${OVERIG_DIR}:/overig
      - ${DEEMIX_DIR}:/deemix
    image: coderaiser/cloudcmd:19.9.6@sha256:44bb5f5132003b08ee621938f90e19474c6d1bbc4c8b225c765b879b8184e9ef
    environment:
      - CLOUDCMD_THEME=dark
    labels:
      - homepage.group=Infra
      - homepage.name=Cloudcommander
      - homepage.icon=cloudcmd.png
      - homepage.href=https://cloudcmd.${DOMAIN}/
      - homepage.description=Filemanager
      - traefik.enable=true
      - traefik.http.routers.cloudcmd.rule=Host(`cloudcmd.${DOMAIN}`)
      - traefik.http.routers.cloudcmd.entrypoints=websecure
      - traefik.http.routers.cloudcmd.middlewares=authentik-forwardauth@docker
      - traefik.http.routers.cloudcmd.tls=true
      - traefik.http.services.cloudcmd.loadbalancer.server.port=8000
    restart: unless-stopped
    user: ${PUID}:${PGID}
    networks:
      - npm
networks:
  npm:
    external: true