services:
  esphome:
    image: ghcr.io/esphome/esphome:2026.8.0@sha256:5ca1a7e39926cdf3cd48239ec5c9f5b429c9ac84390bd940c26c296d3cecc72e
    volumes:
      - ${DOCKER_DATA_DIR}/esphome/config:/config
    environment:
      - ESPHOME_USERNAME=${ESPHOME_USERNAME}
      - ESPHOME_PASSWORD=${ESPHOME_PASSWORD}
    networks:
      my-macvlan-net:
        ipv4_address: ${ESPHOME_IP}
      npm: null
    labels:
      - traefik.enable=true
      - traefik.docker.network=npm
      - traefik.http.routers.esphome.rule=Host(`esphome.${DOMAIN}`)
      - traefik.http.routers.esphome.entrypoints=websecure
      - traefik.http.routers.esphome.tls=true
      - traefik.http.services.esphome.loadbalancer.server.port=6052
      # - homepage.group=Utilities
      # - homepage.name=ESPHome
      # - homepage.icon=esphome.png
      # - homepage.href=https://esphome.${DOMAIN}/
      # - homepage.description=Remote compile server for ESPHome
    restart: unless-stopped
networks:
  npm:
    external: true
  my-macvlan-net:
    external: true