services:
  kometa:
    image: kometateam/kometa:v2.4.4@sha256:90e53a6bdf9343d63702767f8f6d6da09902e7bd174850120ac50d39a0722ff1
    environment:
#      - KOMETA_RUN=true
      - TZ=Europe/Amsterdam
      - KOMETA_PLEX_URL=${PLEX_URL}
      - KOMETA_PLEX_TOKEN=${PLEX_TOKEN}
      - KOMETA_TMDB_API_KEY=${TMDB_API_KEY}
      - KOMETA_TAUTULLI_URL=${TAUTULLI_URL}
      - KOMETA_TAUTULLI_API_KEY=${TAUTULLI_API_KEY}
      - KOMETA_GITHUB_TOKEN=${GITHUB_TOKEN}
      - KOMETA_OMDB_API_KEY=${OMDB_API_KEY}
      - KOMETA_GOTIFY_URL=${GOTIFY_URL}
      - KOMETA_GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - KOMETA_RADARR_URL=${RADARR_URL}
      - KOMETA_RADARR_TOKEN=${RADARR_TOKEN}
      - KOMETA_SONARR_URL=${SONARR_URL}
      - KOMETA_SONARR_TOKEN=${SONARR_TOKEN}
      - KOMETA_TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}
      - KOMETA_TRAKT_CLIENT_SECRET=${TRAKT_CLIENT_SECRET}
      - KOMETA_TRAKT_ACCESS_TOKEN=${TRAKT_ACCESS_TOKEN}
      - KOMETA_TRAKT_REFRESH_TOKEN=${TRAKT_REFRESH_TOKEN}
    container_name: kometa
    volumes:
      - ${DOCKER_DATA_DIR}/kometa/config:/config
    restart: unless-stopped
    networks:
      - npm
networks:
  npm:
    external: true